### ISSUE TITLE
Release 1.5.2 is published but https://quay.io/repository/omrikiei/ktunnel:v1.5.2 is not

### ISSUE THREAD

**Issue by bllfr0g** [omrikiei/ktunnel#107]
Release 1.5.2 does not work out-of-the-box because by default it tries to pull https://quay.io/repository/omrikiei/ktunnel:v1.5.2, which does not exist.

Workaround is to add -i quay.io/omrikiei/ktunnel:latest to the command line to override the default.

**Comment by omrikiei** [comment]
on it

**Comment by omrikiei** [comment]
migrated to [docker.io/omrieival/ktunnel](docker.io/omrieival/ktunnel)
