### ISSUE TITLE
ERRO[0007] Error sending init tunnel request: rpc error: code = Unavailable

### ISSUE THREAD

**Issue by outbounder** [omrikiei/ktunnel#11]
Hi @omrikiei :)

Its me again, this time with the following:

```
2020-02-06 09:52:13 >| $ ktunnel expose myWebapp 8084:8084 -n myNamespace
INFO[0000] Exposed service's cluster ip is: 10.31.10.100
INFO[0000] waiting for deployment to be ready           
INFO[0007] All pods located for port-forwarding         
INFO[0007] Waiting for port forward to finish           
INFO[0007] Forwarding from 127.0.0.1:28688 -> 28688
Forwarding from [::1]:28688 -> 28688 
INFO[0007] starting tcp tunnel from source 8084 to target 8084 
E0206 09:52:21.785327   10875 portforward.go:400] an error occurred forwarding 28688 -> 28688: error forwarding port 28688 to pod 3ddcdef600c6c0d884e3d71f5600a350623786083794ac4ef3a330c5ddc2944b, uid : exit status 1: 2020/02/06 07:52:21 socat[165522] E connect(5, AF=2 127.0.0.1:28688, 16): Connection refused
ERRO[0007] Error sending init tunnel request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed 
INFO[0023] Got exit signal, closing client tunnels and removing k8s objects 
INFO[0023] Deleting service myWebapp
```

I'll appreciate :heart_eyes: any clues as always :)

Kind regards,
Boris

**Comment by omrikiei** [comment]
Good morning, could it be that the port(28688) is already taken by another application?
Is it possible that another instance of ktunnel is running and occupying this port?

**Comment by outbounder** [comment]
Good morning sir :)

Well I've tried with different port (several times) but with no avail. 

Also I'm trying to find the pod but neither `kubectl describe pod <uid>` nor `kubectl get pods` include ktunnel's pod... 

For `<uid>` I'm using the strange hash from the output logs (but doubt that is the case :) ).

**Comment by outbounder** [comment]
Update: found the deployment and the ktunnel's pod (after realizing that they are with the exposed service name)

The pod's logs are as follows:

```
time="2020-02-06T08:36:33Z" level=error msg="Failed getting kubernetes config: stat /.kube/config: no such file or directory"
time="2020-02-06T08:36:33Z" level=info msg="Starting to listen on port 8000"
```

**Comment by omrikiei** [comment]
So that seems weird - ktunnel is listening on port 8000 :\
And it's weird because the only whey to change it is with an explicit flag.. i'm looking into this

**Comment by omrikiei** [comment]
@outbounder can you extract the deployment spec for the ktunnel server and paste it here please?

**Comment by outbounder** [comment]
@omrikiei Sorry for the `port 8000` mislead, I'm just testing with different ports ;) 

Without executing `ktunnel expose ... -p 8000` it listens on the default port 28688 as expected but still there is fatal error for `kube/config`

Here are up-to-date issue details

## Steps to reproduce

1. execute `$ ktunnel expose myWebapp 8084:8084 -n myNamespace -v`

### output

```
INFO[0000] Exposed service's cluster ip is: 10.31.245.162 
INFO[0000] waiting for deployment to be ready           
INFO[0006] All pods located for port-forwarding         
INFO[0006] Waiting for port forward to finish           
INFO[0006] Forwarding from 127.0.0.1:28688 -> 28688
Forwarding from [::1]:28688 -> 28688 
INFO[0006] starting tcp tunnel from source 8084 to target 8084 
E0206 10:53:04.831638   11448 portforward.go:400] an error occurred forwarding 28688 -> 28688: error forwarding port 28688 to pod 83b0bbe90c79f7a76c732bd60679318c3a4fe5a91fe3b97e666942db9aebe6eb, uid : exit status 1: 2020/02/06 08:53:04 socat[179274] E connect(5, AF=2 127.0.0.1:28688, 16): Connection refused
ERRO[0006] Error sending init tunnel request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed 
```

### myWebapp pod logs

```
time="2020-02-06T08:53:09Z" level=error msg="Failed getting kubernetes config: stat /.kube/config: no such file or directory"
time="2020-02-06T08:53:09Z" level=info msg="Starting to listen on port 28688"
```

**Comment by omrikiei** [comment]
@outbounder, I tried reproducing the same behaviour without success. Does your cluster have any security policy or or a security application?

Another thing I'm looking at is that by the server logs it started listening on 08:53:09 while socat failed at 08:53:04, but this assumption ignores any time differences between your local machine and the kubernetes node.

**Comment by omrikiei** [comment]
Hey @outbounder, just checking if you had a chance to play around with this functionality again...

**Comment by outbounder** [comment]
Hey @omrikiei , I've just tested successfully with [v1.1.10](https://github.com/omrikiei/ktunnel/releases/tag/v1.1.10) so I guess this is some sort of false positive. 

Closing the issue, will reopen in case the problem raises.

Thanks for the amazing work and wonderful support! :bowing_man:
