### ISSUE TITLE
New version of ktunnel

### ISSUE THREAD

**Issue by vandot** [omrikiei/ktunnel#116]
Wanted to check if you planned to release new version. I use nix for installation and it would be great to include all the latest changes to the code :)

**Comment by kayneb** [comment]
+1, would love to make use of the ability to define custom local hostnames add in https://github.com/omrikiei/ktunnel/commit/1b18482861eb89acdaf168359fc1f5cf1a381df6

**Comment by omrikiei** [comment]
done, sorry for the long wait time.. I'll try to do better

**Comment by kayneb** [comment]
Thanks a lot! This is such a great tool.
