### ISSUE TITLE
Add resource request for injected ktunnel server sidecar

### ISSUE THREAD

**Issue by jonastim** [omrikiei/ktunnel#19]
Thanks for the great tool, @omrikiei!

I ran into a small issue on my Kubernetes cluster. The injected sidecar doesn't specify any resource request (`resources: {}` in the deployment yaml) which the cluster doesn't allow. My workaround is to manually edit the yaml and add CPU and memory limits and requests to unblock the deployment. 
Could you add a reasonable default to make that step unnecessary?

**Comment by omrikiei** [comment]
Hey @jonastim, i'll try to take a look over the weekend, thanks you

**Comment by omrikiei** [comment]
releasing a version that requests 500m for the injected pod, is your cluster enforcing both requests and limits and both cpu and memory?

**Comment by jonastim** [comment]
Great! Yes, in the Replica Set event log the error is `Error creating: pods <pod name> is forbidden: failed quota: cpu-mem-hard-limits: must specify cpu, memory`

**Comment by omrikiei** [comment]
👍 so I'll need to refine this change, will release a newer minor version in the tonight

**Comment by omrikiei** [comment]
should be working in release [v1.2.5](https://github.com/omrikiei/ktunnel/releases/tag/v1.2.5), could you please verify?

**Comment by jonastim** [comment]
Works great 👍 
I couldn't install through brew and grabbed the binary. 
It says version 1.2.4 but I assume it was just forgotten to bump somewhere.
```
❯ ~/Downloads/ktunnel_1.2.5_Darwin_x86_64/ktunnel --version
ktunnel version 1.2.4
```

**Comment by omrikiei** [comment]
Yes, will take care of this soon, closing.
