### ISSUE TITLE
Kubectl plugin

### ISSUE THREAD

**Issue by tamasfe** [omrikiei/ktunnel#46]
Providing ktunnel as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) and exposing commands like `kubectl tunnel expose ...` would help with distribution and updates.

**Comment by omrikiei** [comment]
this is a great idea @tamasfe, I'll try to make it happen soon

**Comment by omrikiei** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/1280 in the works..

**Comment by omrikiei** [comment]
plugin is hosted at krew, readme updated 👍
