### ISSUE TITLE
Issue waiting for pod to be ready after injecting

### ISSUE THREAD

**Issue by sjones512** [omrikiei/ktunnel#47]
I believe there is an issue waiting for the newly injected pod to be ready.

`injector.go:28 waitForReady(&o.Name, o.GetCreationTimestamp().Time, *o.Spec.Replicas, readyChan)`

This line seems to always use the creation timestamp of the deployment which is not updated when the deployment is modified. I think we're on Kubernetes 1.19.

Perhaps I'm misunderstanding the code but don't we want a pod created after the the current time in this scenario?  

Issue seems to manifest for me as sometimes having to run the inject command 2x. The first time in updates the deployment and then tries to connect to the pod that existed before the deployment was changed.

The second time it detects the sidecar and creates the tunnel successfully.

Thanks.

**Comment by omrikiei** [comment]
tested and merged, thank you again @sjones512
