### ISSUE TITLE
ktunnel v1.3.9 killed on Mac OS Big Sur

### ISSUE THREAD

**Issue by amenuor** [omrikiei/ktunnel#55]
## Description
On Mac OS Big Sur (Version 11.3.1) running ktunnel 1.3.9 results in process being terminated with SIGKILL

## Expected Behavior
We would expect ktunnel to work normally

## Current Behavior

Even a simple invocation, just invoking the command ktunnel without any argument, results in the process being killed

```
$ ktunnel
[1]    35494 killed     ktunnel
```

## Steps to Reproduce
1. `brew tap omrikiei/ktunnel && brew install ktunnel` or `brew upgrade ktunnel` if already installed
2. run `ktunnel`

## Work around

Build 1.3.8 from source:

```sh
brew uninstall ktunnel
git clone https://github.com/omrikiei/ktunnel.git
git checkout tags/v1.3.8
CGO_ENABLED=0 go build -l$dflags="-s -w"
./ktunnel
```

**Comment by omrikiei** [comment]
Hi @amenuor,
I'm trying to get a hold of a big sur machine to check it, in the meanwhile - would you mind sending me the following trace on version 1.3.9? does it also happen when building 1.3.9 from source?
`sudo dtruss ktunnel`

**Comment by amenuor** [comment]
Hi @omrikiei,
sure, output from the trace: 

```
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute ktunnel: Cannot allocate memory
```

Now the interesting bit: when building both tags/v1.3.9 and HEAD the problem is not there, everything runs smoothly.
The issue happens when installing from brew

**Comment by omrikiei** [comment]
thank you @amenuor , I think UPX was causing it so removed it from the actions pipeline, could you check with v1.4.0?

**Comment by amenuor** [comment]
Hello @omrikiei,
1.4.0 works like a charm. Great work!

**Comment by amenuor** [comment]
Hello @omrikiei,
1.4.0 works like a charm. Great work!
