### ISSUE TITLE
Brew install on Big Sur Mac ARM fails

### ISSUE THREAD

**Issue by nickgronow** [omrikiei/ktunnel#56]
I have tried lots of variants of installing with brew and getting the following:

```bash
➜  brew tap omrikiei/ktunnel && brew install --HEAD ktunnel
==> Installing ktunnel from omrikiei/ktunnel
==> Cloning https://github.com/omrikiei/ktunnel.git
Updating /Users/nick/Library/Caches/Homebrew/ktunnel--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 03424c3 updated docs
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - ktunnel
```

**Comment by omrikiei** [comment]
Hi @nickgronow,
is this not working for you?
`brew tap omrikiei/ktunnel && brew install omrikiei/ktunnel/ktunnel`

**Comment by nickgronow** [comment]
This is what I get:

```bash
➜  brew tap omrikiei/ktunnel && brew install omrikiei/ktunnel/ktunnel
Error: omrikiei/ktunnel/ktunnel is a head-only formula.
To install it, run:
  brew install --HEAD omrikiei/ktunnel/ktunnel
```

**Comment by omrikiei** [comment]
@nickgronow is this after removing+untapping an re-tapping to the tap? 
the [formula](https://github.com/omrikiei/homebrew-ktunnel/blob/master/ktunnel.rb) itself is not head-only..
could you try removing, untapping and readding and installing the package?

**Comment by omrikiei** [comment]
Hey @nickgronow - is this issue still ongoing?

**Comment by omrikiei** [comment]
Issue is stale thus being closed, @nickgronow kindly re-open if you encounter this issue again

**Comment by nickgronow** [comment]
Will do.  I can't remember how I got it running.  I will investigate and let you know if I encounter it again,.
