### ISSUE TITLE
Tunneling doesn't work

### ISSUE THREAD

**Issue by MShekow** [omrikiei/ktunnel#61]
On Windows 10, Docker for Windows and using a k3d cluster, the tunnel cannot be established.

On the host, when running something like `ktunnel expose debuggerhost 4321:4321` I get the following messages:
```
time="2021-08-10T16:50:36+02:00" level=info msg="port forwarding to https://http:/api/v1/namespaces/default/pods/debuggerhostt-6c76f898fd-vhmw2/portforward"
time="2021-08-10T16:50:36+02:00" level=info msg="Waiting for port forward to finish"
time="2021-08-10T16:50:49+02:00" level=error msg="error upgrading connection: error sending request: Post \"https://http/api/v1/namespaces/default/pods/debuggerhostt-6c76f898fd-vhmw2/portforward\": dial tcp: lookup http: no such 
host"
```

The first line already looks wrong to me.

**Comment by omrikiei** [comment]
Hey @MShekow - sorry for taking a while to address this..
I released a beta version that's supposed to have a fix for this - could you try and test it out please and see if it fixes your issue?
you can get it [here](https://github.com/omrikiei/ktunnel/releases/tag/v1.4.2-beta)

**Comment by MShekow** [comment]
No worries. I can confirm that the tunnel can be established with the 1.4.2 beta.

**Comment by omrikiei** [comment]
Yey! releasing and closing!
