### ISSUE TITLE
Is license MIT or GPL 3?

### ISSUE THREAD

**Issue by areller** [omrikiei/ktunnel#64]
About section says license is GPL 3
![image](https://user-images.githubusercontent.com/15989650/131771838-b0cd919b-fc28-450e-bcdb-754f7b8b1c54.png)

But README says it's MIT
![image](https://user-images.githubusercontent.com/15989650/131771859-18869aca-c47e-4ca5-829d-8d717c9716a5.png)

Which one is it?

**Comment by omrikiei** [comment]
it was recently changed to GPL-3.0 - I'll make sure to update the README as well.. nevertheless - if you find this license problematic for a use case feel free to reach out :)
