### ISSUE TITLE
Deployment can't get image - v1.4.7 missing on quay.io

### ISSUE THREAD

**Issue by okletzmayr** [omrikiei/ktunnel#75]
Thanks a bunch for this awesome tool, I just found it yesterday!
When I upgraded to 1.4.7 today, new tunnel deployments get stuck on image pull.
Seems like the [container registry](https://quay.io/repository/omrikiei/ktunnel) is missing the v1.4.7 image tag. I'd be grateful if this gets fixed.

**Comment by omrikiei** [comment]
Fixed manually, automated build failed due to quay.io rate limiting, I intend to move to a new registry soon.
Can you confirm it works now?

**Comment by okletzmayr** [comment]
The deployments work now - thank you!
