### ISSUE TITLE
latest version on brew is 1.4.7 and not 1.4.8

### ISSUE THREAD

**Issue by sTb1337** [omrikiei/ktunnel#89]
brew doesn't know v 1.4.8.

` brew update
Already up-to-date.
brew tap omrikiei/ktunnel && brew install omrikiei/ktunnel/ktunnel
Warning: omrikiei/ktunnel/ktunnel 1.4.7 is already installed and up-to-date.
To reinstall 1.4.7, run:
  brew reinstall ktunnel`

is there anything I did wrong?

**Comment by omrikiei** [comment]
fixed, sorry
